name: Linux Build

on:
  push:
    branches: "*"
  pull_request:
    branches: "*"

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: make
      run: cd src && make
